type DogAttribute {
  key: ID!
  value: String
}

type Dog {
  name: ID!;
  attributes: [DogAttribute];
  description: [String];
  image: String;
  ageInWeeks: Number;
  sex: String;
  breed: String;
  color: String;
  fee: Number;
  weight: Number;
  availableDate: String;
}
