export { default as TBody } from './TBody'
export { default as TCell } from './TCell'
export { default as THead } from './THead'
export { default as TRow } from './TRow'
export { default as TTable } from './TTable'
export { default as TWrapper } from './TWrapper'